refactor: shfmt, shellharden and fix shellcheck errors

diff --git a/root/app/healthcheck b/root/app/healthcheck
--- a/root/app/healthcheck
+++ b/root/app/healthcheck
@@ -9,27 +9,29 @@
 HOST="$HEALTH_CHECK_HOST"
 
 if [[ -z "$HOST" ]]; then
-    echo "Host not set! Set env 'HEALTH_CHECK_HOST'. For now, using default google.com"
-    HOST="google.com"
+	echo "Host not set! Set env 'HEALTH_CHECK_HOST'. For now, using default google.com"
+
+	HOST="google.com"
 fi
 
 ### DNS check
-if ! nslookup $HOST > /dev/null; then
-    echo "DNS resolution failed"
-    exit 1
+if ! nslookup "$HOST" >/dev/null; then
+	echo "DNS resolution failed"
+	exit 1
 fi
 
 ### Ping check
 # Get at least 2 responses and timeout after 10 seconds
 if ! ping -c 2 -w 10 "$HOST"; then
-    echo "Network is down"
-    exit 1
+	echo "Network is down"
+	exit 1
 fi
 
 echo "Network is up"
 
 ### Service check
 # Expected output is 2, 1 for process and 1 for grep
+# shellcheck disable=2312
 TRANSMISSION="$(pgrep transmission | wc -l)"
 
 if [[ "$TRANSMISSION" -ne 1 ]]; then
@@ -38,5 +40,4 @@ if [[ "$TRANSMISSION" -ne 1 ]]; then
 fi
 
 echo "transmission-daemon process is running"
-
 exit 0
